// Centralized enums for lead statuses to avoid exporting enums from React components

export enum LeadConnectionStatus {
  NOT_STARTED = 'NOT_STARTED',
  INITIATED = 'INITIATED',
  CONNECTION_EXISTS = 'CONNECTION_EXISTS',
  CONNECTION_SENT = 'CONNECTION_SENT',
  CONNECTION_RECEIVED = 'CONNECTION_RECEIVED',
  CONNECTION_ACCEPTED = 'CONNECTION_ACCEPTED',
  INVITATION_EXISTS = 'INVITATION_EXISTS',
  SKIPPED = 'SKIPPED',
}

export enum LeadEngagementStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_SEQUENCE = 'IN_SEQUENCE',
  ALREADY_ENGAGED = 'ALREADY_ENGAGED',
  SUCCESSFULLY_ENGAGED = 'SUCCESSFULLY_ENGAGED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  SKIPPED = 'SKIPPED',
}


